name: Project Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          cd ..
          python -m pip install --upgrade pip
          pip install -r dataengineer/requirements.txt
      - name: Run tests
        run: |
          python data_engineer/tests/test1.py


