name: Project Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ..
          pwd
          echo "pickle5==0.0.11" > requirements.txt
          pwd
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python test1.py


